ALTER TABLE users
DROP COLUMN IF EXISTS phone_number,
DROP COLUMN IF EXISTS country_code,
DROP COLUMN IF EXISTS phone_e164,
DROP COLUMN IF EXISTS profile_image_url;

ALTER TABLE attendee_profiles
ADD COLUMN country_code VARCHAR(5) NOT NULL,
ADD COLUMN phone_number VARCHAR(20) NOT NULL,
ADD COLUMN phone_e164 VARCHAR(25) NOT NULL UNIQUE;